# Generated by Django 5.2.3 on 2025-07-19 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('company_logo', models.ImageField(upload_to='logos/')),
                ('industry', models.CharField(max_length=100)),
                ('industry_other', models.CharField(blank=True, max_length=255, null=True)),
                ('company_origin', models.CharField(max_length=100)),
                ('year_founded', models.DateField()),
                ('description', models.TextField()),
                ('problem_solution', models.TextField()),
                ('competitive_advantage', models.TextField()),
                ('funding_goal', models.FloatField()),
                ('valuation', models.FloatField()),
                ('equity_offered', models.FloatField()),
                ('funding_deadline', models.DateField()),
                ('min_investment', models.FloatField()),
                ('risk_factors', models.TextField(blank=True)),
                ('risk_other_specify', models.CharField(blank=True, max_length=255, null=True)),
                ('revenue_2023', models.FloatField(blank=True, null=True)),
                ('profit_2023', models.FloatField(blank=True, null=True)),
                ('assets_2023', models.FloatField(blank=True, null=True)),
                ('revenue_2022', models.FloatField(blank=True, null=True)),
                ('profit_2022', models.FloatField(blank=True, null=True)),
                ('assets_2022', models.FloatField(blank=True, null=True)),
                ('revenue_2021', models.FloatField(blank=True, null=True)),
                ('profit_2021', models.FloatField(blank=True, null=True)),
                ('assets_2021', models.FloatField(blank=True, null=True)),
                ('pitch_deck', models.FileField(upload_to='documents/')),
                ('financial_statements', models.FileField(upload_to='documents/')),
                ('legal_documents', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('additional_materials', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('usertype', models.CharField(default='investor', max_length=50)),
            ],
        ),
    ]
