# Generated by Django 5.2.3 on 2025-07-19 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('companyname', models.CharField(max_length=255)),
                ('company_logo', models.ImageField(upload_to='invested/')),
                ('industry', models.CharField(max_length=50)),
                ('amount', models.FloatField()),
                ('equity', models.FloatField()),
                ('method', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('pitch_deck', models.FileField(upload_to='invested/')),
                ('financial_statements', models.FileField(upload_to='invested/')),
                ('legal_documents', models.FileField(blank=True, null=True, upload_to='invested/')),
                ('additional_materials', models.FileField(blank=True, null=True, upload_to='invested/')),
            ],
        ),
    ]
