# Generated by Django 5.2.3 on 2025-07-19 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_invest'),
    ]

    operations = [
        migrations.AddField(
            model_name='invest',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
