# Generated by Django 5.2.3 on 2025-07-19 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_invest_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='invest',
            name='valuation',
            field=models.FloatField(null=True),
        ),
    ]
