# Generated by Django 5.2.3 on 2025-07-19 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_invest_valuation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invest',
            name='company_logo',
            field=models.ImageField(upload_to='logos/'),
        ),
    ]
