# Generated by Django 5.2.3 on 2025-07-19 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_alter_invest_company_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invest',
            name='additional_materials',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='invest',
            name='financial_statements',
            field=models.FileField(upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='invest',
            name='legal_documents',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='invest',
            name='pitch_deck',
            field=models.FileField(upload_to='documents/'),
        ),
    ]
