# Generated by Django 5.2.3 on 2025-07-20 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_alter_invest_additional_materials_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invest',
            name='additional_materials',
        ),
        migrations.RemoveField(
            model_name='invest',
            name='company_logo',
        ),
        migrations.RemoveField(
            model_name='invest',
            name='companyname',
        ),
        migrations.RemoveField(
            model_name='invest',
            name='email',
        ),
        migrations.RemoveField(
            model_name='invest',
            name='financial_statements',
        ),
        migrations.RemoveField(
            model_name='invest',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='invest',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='invest',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='invest',
            name='legal_documents',
        ),
        migrations.RemoveField(
            model_name='invest',
            name='pitch_deck',
        ),
        migrations.AddField(
            model_name='invest',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.documents'),
        ),
        migrations.AddField(
            model_name='invest',
            name='investor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.info'),
        ),
    ]
