# Generated by Django 5.2.3 on 2025-07-20 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_remove_invest_additional_materials_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invest',
            old_name='date',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='invest',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='invest',
            name='equity',
        ),
        migrations.RemoveField(
            model_name='invest',
            name='investor',
        ),
        migrations.RemoveField(
            model_name='invest',
            name='method',
        ),
        migrations.RemoveField(
            model_name='invest',
            name='valuation',
        ),
        migrations.AddField(
            model_name='invest',
            name='additional_materials',
            field=models.FileField(blank=True, null=True, upload_to='extras/'),
        ),
        migrations.AddField(
            model_name='invest',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='invest',
            name='financial_statements',
            field=models.FileField(null=True, upload_to='financials/'),
        ),
        migrations.AddField(
            model_name='invest',
            name='firstname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='invest',
            name='lastname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='invest',
            name='legal_documents',
            field=models.FileField(null=True, upload_to='legal_docs/'),
        ),
        migrations.AddField(
            model_name='invest',
            name='pitch_deck',
            field=models.FileField(null=True, upload_to='pitch_decks/'),
        ),
        migrations.AddField(
            model_name='invest',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.info'),
        ),
    ]
