# Generated by Django 5.2.3 on 2025-07-20 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_rename_date_invest_timestamp_remove_invest_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invest',
            name='amount',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='invest',
            name='company_logo',
            field=models.ImageField(null=True, upload_to='logos/'),
        ),
        migrations.AddField(
            model_name='invest',
            name='companyname',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invest',
            name='equity',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='invest',
            name='industry',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='invest',
            name='valuation',
            field=models.FloatField(null=True),
        ),
    ]
