# Generated by Django 5.2.3 on 2025-07-20 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_invest_amount_invest_company_logo_invest_companyname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invest',
            name='method',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
