# Generated by Django 5.2.3 on 2025-07-26 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_invest_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documents',
            name='industry_other',
        ),
        migrations.RemoveField(
            model_name='documents',
            name='risk_other_specify',
        ),
    ]
